export const DISPLAY_PROJECT_MODAL = 'DISPLAY_PROJECT_MODAL';
export const DISPLAY_CONFIRMATION_MODAL = 'DISPLAY_CONFIRMATION_MODAL';
export const DISPLAY_ACTION_MODAL = 'DISPLAY_ACTION_MODAL';
export const MODAL_TRANSITION_DURATION = 300;
